### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'max'

### ISSUE THREAD

**Issue by zhang-pan** [sail-sg/volo#10]
When I use the code to use the pre-training model for training, I find that the data becomes tuple data when passing through the model, resulting in the model can not continue training。
    model = volo_d2()
    load_pretrained_weights( model,'./path/to/pretrained/weights/d2_224_85.2.pth.tar', use_ema=False, strict=False,num_classes=2)
    print(model)
......
def train(train_loader,model,criterion, optimizer, epoch,args,scheduler=None):
    print("train--------------")
    avg_loss=0
    avg_acc=0
    model.train()
    for batch_idx,(image,target) in enumerate(train_loader):
        # measure data loading time
        image,target=Variable(image.cuda()),Variable(target.cuda())
        print(type(image))
        image=image.cuda()
        target=target.cuda()
        optimizer.zero_grad()
        logits =model(image)

        #m = [t.cpu().numpy() for t in logits]
        #m = [o.cpu().detach() for o in m]
        #logits = torch.tensor(m)
        #logits = torch.tensor([item.cpu().detach().numpy() for item in logits]).cuda()

        print(type(logits))

    preds=logits.max(1, keepdim=True)[1] # get the index of the max log-probability
AttributeError: 'tuple' object has no attribute 'max'

**Comment by zihangJiang** [comment]
Volo returns classification logits as well as a dense score map for all tokens.
https://github.com/sail-sg/volo/blob/1f67923404d85cb8012a61b35d7eff782fe90cef/models/volo.py#L643-L645
For fine-tuning, I think you can use only the first element of the output.

**Comment by zhang-pan** [comment]
> Volo returns classification logits as well as a dense score map for all tokens.
> https://github.com/sail-sg/volo/blob/1f67923404d85cb8012a61b35d7eff782fe90cef/models/volo.py#L643-L645
> 
> 
> For fine-tuning, I think you can use only the first element of the output.

thank you for your reply, it is very helful for me.
