### ISSUE TITLE
UnboundLocalError: local variable 'input' referenced before assignment

### ISSUE THREAD

**Issue by zhang-pan** [sail-sg/volo#11]
When I run the main program with "python main. py . /data", the following error occurs:
D:\Python36\lib\site-packages\torchvision\transforms\transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "main.py", line 948, in <module>
    main()
  File "main.py", line 664, in main
    optimizers=optimizers)
  File "main.py", line 746, in train_one_epoch
    for batch_idx, (input, target) in enumerate(loader):
  File "D:\Python36\lib\site-packages\tlt\data\loader.py", line 105, in __iter__
    yield input, target
UnboundLocalError: local variable 'input' referenced before assignment

Please give me more advice and look forward to your reply. thank you very much.

**Comment by yuanli2333** [comment]
If you want to train our models, following the [training scripts](https://github.com/sail-sg/volo#4-train).
