### ISSUE TITLE
TypeError: forward() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by YHDASHEN** [sail-sg/volo#22]
Hi,

when I used volo_d1 pretrained model for my training. I loaded this model successfully. But I received this error when I do the training step. Could you please give me some hint? Here is the input before forward() function I traced. The original one is resnet18, it worked fine.
[d1_224.txt](https://github.com/sail-sg/volo/files/6758639/d1_224.txt)
[resnet18.txt](https://github.com/sail-sg/volo/files/6758641/resnet18.txt)

Thank you in advance.

Best regards,
Hui Yu

**Comment by yuanli2333** [comment]
The output of volo includes https://github.com/sail-sg/volo/blob/1f67923404d85cb8012a61b35d7eff782fe90cef/models/volo.py#L643-L645,
For normal training, you only need x_cls,
 you may want to refer to this [issue](https://github.com/sail-sg/volo/issues/10).

**Comment by YHDASHEN** [comment]
Could you please send me the structure of VOLO model?
