### ISSUE TITLE
Colab Notebook doesn't work & gives wrong results.

### ISSUE THREAD

**Issue by debparth** [sail-sg/volo#29]
Hi Creators, Thanks for making a new SOTA models & also for open-sourcing it.

I was trying the colab notebook and it's throwing an error!!
![image](https://user-images.githubusercontent.com/53347017/126310480-2afdacfc-17ab-4b57-8975-6fb00d1f242a.png)

After going through the [`Usage`](https://github.com/sail-sg/volo#usage) and adding those params. It gave me different and wrong results compared to demo colab Notebook.
![image](https://user-images.githubusercontent.com/53347017/126311176-b72e2703-1e6c-4b59-8c2a-61bc1e2662e3.png)

**Comment by zihangJiang** [comment]
Hi @debparth , could you please try to run it again to see if it works now?

**Comment by debparth** [comment]
Hi @zihangJiang, Thanks for quick reply. It's working now. Can I ask you what was the bug which caused this mess?

**Comment by zihangJiang** [comment]
It's caused by using the wrong version of `tlt` package. It would be better to specify the version of the required packages as stated here https://github.com/sail-sg/volo#1-requirements to avoid potential bugs.

**Comment by debparth** [comment]
@zihangJiang Oh... I see. Thank you.
