### ISSUE TITLE
Finetune with 512 image size

### ISSUE THREAD

**Issue by javierrodenas** [sail-sg/volo#30]
Hello,

I am finetuning a model with an image size of 512 and `--token-label-size 24`. Is the label size enough for 512 image size? Should I use a higher label size? How do I really know the correct label size?

Thank you in advance!

**Comment by zihangJiang** [comment]
The label size is related to the number of output tokens. For VOLO, if `image size = 224`, then the token label size should be `224/16=14`. So for your case, when `image size = 512`, the label size should be `512/16=32`.

**Comment by javierrodenas** [comment]
Thanks, I close the issue.
